### ISSUE TITLE
Not working with HA 2025.1

### ISSUE THREAD

**Issue by grahambrown11** [mac-zhou/midea-ac-py#225]
**Describe the bug （描述一下问题）**
HA 2025.1 has removed some deprecations and now this integration fails to start.

**Screenshots / Logs / Pcap File（屏幕截图/日志/抓包文件）**
ImportError: cannot import name 'SUPPORT_TARGET_TEMPERATURE' from 'homeassistant.components.climate.const'

**Versions (版本信息)**
 - Home Assistant version: 2025.1
 - Midea msmart version: 0.2.3

**Comment by bitbrain-za** [comment]
Looks like it's a result of this PR
https://github.com/home-assistant/core/pull/131798

**Comment by bitbrain-za** [comment]
I've rolled back to the last 2024 version until there's a fix
From the terminal:
`ha core update --version 2024.12.5`

**Comment by mill1000** [comment]
You should try my fork: https://github.com/mill1000/midea-ac-py

I'm actively maintaining it and keeping up with the latest HA changes.

**Comment by bitbrain-za** [comment]
> You should try my fork: https://github.com/mill1000/midea-ac-py
> 
> I'm actively maintaining it and keeping up with the latest HA changes.

Works like a charm, thank you
